apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: helloworld-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: helloworld
    minReplicas: 1
    maxReplicas: 1
    metrics:
        - resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
          type: Resource
        - resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 90
          type: Resource
    behavior:
        scaleDown:
            policies:
                - type: Percent
                  value: 50
                  periodSeconds: 60
